@extends('layouts.admin.boardTemplate')
@section('main_head')
    @parent
    <link href="{{ URL::asset('admin/css/admin.css') }}" type="text/css" rel="stylesheet"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
@stop

@section('content')
    <div class="admin-container">
        <div class="panel panel-primary">
            <div class="panel-heading panou-titlu">
                @if( ! empty($_GET['scope']) && $_GET['scope'] == 'edit' )
                    <i class="fa fa-pencil" aria-hidden="true"></i> Edit page
                    @else
                    <i class="glyphicon glyphicon-plus"></i> Create a new page
                    @endif
            </div>
            <div class="panel-body">

                {!! Form::open(['id' => 'create-new-page']) !!}
                <div class="form-group">
                    {!! Form::label('title', 'Page Title') !!}
                    {!! Form::text('title', null, ['class' => 'form-control']) !!}
                </div>
                <div class="form-inline">
                    <div class="form-droup">
                        <div class="radio">
                            <label><b>Use autogenerated URL based on title</b></label>
                            <input id="default" name="url" type="radio" checked value="default">
                        </div>
                        &nbsp;&nbsp;&nbsp;
                        <div class="radio">
                            <label><b>Use custom URL</b></label>
                            <input id="custom" name="url" type="radio" value="custom">
                        </div>

                    </div>
                </div>
                <small>By default, a based on title URL is autogenerated. If you want to use a custom url, check 'Use
                    custom URL' option.
                </small>
                <div class="form-group">
                    <div class="input-group">
                        {{--*/  $domain = $_SERVER['SERVER_NAME'];  /* --}}
                        <span class="input-group-addon">{{ $domain }}/pages/</span>
                        <input id="custom-input" type="text" class="form-control">
                    </div>
                </div>
                <b>Page content</b>
                <textarea id="textarea"></textarea>

                <br>
                <button type="submit" class="btn-lg btn-success"><i class="fa fa-floppy-o" aria-hidden="false"></i>&nbsp;
                    Save page
                </button>
                {!! Form::close() !!}
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Page saved</h4>
                </div>
                <div class="modal-body">
                    <div class="alert alert-success">
                        <h4>
                            <b>New page saved successfully!</b>
                        </h4>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

@stop

@section('foot')
    @parent
    <script src="{{ URL::asset('admin/tinymce/tinymce.min.js') }}"></script>
    <script src="{{ URL::asset('admin/js/page.js') }}"></script>
    <script>
        $(function () {
            $('#custom-input').css('pointer-events', 'none');
            $('#custom').on('change', function () {
                $('#custom-input').css('pointer-events', 'auto');
            });
            $('#default').on('change', function () {
                $('#custom-input').css('pointer-events', 'none');
            });

            //slugify title
            $('#title').on('keyup', function () {
                if ($('#custom').prop('checked') == false) {
                    var title = $('#title').val();
                    var slugedTitle = convertToSlug(title);
                    $('#custom-input').val(slugedTitle);
                }
            });

            //populate inputs if scope = edit
            @if( ! empty($_GET['scope']) && $_GET['scope'] == 'edit' )
                       @foreach($pages as $page)
                       @if( ! empty($_GET['pageid']) &&  $page->id  == $_GET['pageid'])
                       $('#title').val('{{ $page->title }}');
                       $('#custom-input').val('{{ $page->url }}');
            {{--*/ $content = json_encode($page->content);  /*--}}
            var content = {!! $content !!};
            $('#textarea').text(content);
            @endif
             @endforeach
                 @endif

 addTinymce();
        });

        function addTinymce() {
            tinymce.init({
                mode: "none",
                force_br_newlines: false,
                force_p_newlines: false,
                forced_root_block: '',
                menubar: false,
                selector: '#textarea',
                height: 300,
                theme: 'modern',
                cleanup : false,
                verify_html : false,
                relative_urls: false,
                remove_trailing_brs: false,
                plugins: [
                    'advlist autolink lists link image charmap preview hr anchor pagebreak',
                    'searchreplace wordcount visualblocks visualchars code fullscreen',
                    'insertdatetime media nonbreaking save table contextmenu directionality',
                    'emoticons template paste textcolor colorpicker textpattern imagetools toc'
                ],
                toolbar1: 'undo redo | insert | formatselect | fontselect | bold italic underline strikethrough | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | print preview media | forecolor backcolor emoticons | code ',
                image_advtab: true,
                templates: [
                    {title: 'Test template 1', content: 'Test 1'},
                    {title: 'Test template 2', content: 'Test 2'}
                ],
                file_browser_callback: elFinderBrowser

            });

        }


        function elFinderBrowser(field_name, url, type, win) {
            tinymce.activeEditor.windowManager.open({
                file: '<?= route('elfinder.tinymce4') ?>',
                title: 'Choose an image',
                width: 900,
                height: 450,
                resizable: 'yes'
            }, {
                setUrl: function (url) {
                    win.document.getElementById(field_name).value = url;
                }
            });
            return false;
        }


        function convertToSlug(Text) {
            return Text
                    .toLowerCase()
                    .replace(/ /g, '-')
                    .replace(/[^\w-]+/g, '')
                    ;
        }
    </script>

@stop